default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['FIXDBACKEND_DATABASE'] %>
  username: <%= ENV['FIXDBACKEND_DATABASE_USERNAME'] %>
  password:  <%= ENV['FIXDBACKEND_DATABASE_PASSWORD'] %>
  host: <%= ENV['FIXDBACKEND_DATABASE_HOST'] %>
  port: <%= ENV['ATTENDANCEBACKEND_DATABASE_PORT'] %>
    
test:
  <<: *default
  database: <%= ENV['FIXDBACKEND_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['FIXDBACKEND_DATABASE'] %>
